version: "3.9"
services:
  ui:
    build: ./front-end
    ports:
      - "8080:80"
    depends_on:
      - api
  api:
    build: ./back-end
    ports:
      - "5000:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Futurity1"
      ACCEPT_EULA: "Y"
